export const API = {
  GET_SUDOKU: 'sudoku/',
  HISTORY_ENTRY_EXISTS: 'history/sudoku/',
  UPDATE_HISTORY_ENTRY: 'history/',
  GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY: 'sudoku/random/difficulty/'
};

export const GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_SUCCESS = 'GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_SUCCESS';
export const GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_ERROR = 'GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_ERROR';

export const GET_SUDOKU_SUCCESS = 'GET_SUDOKU_SUCCESS';
export const GET_SUDOKU_ERROR = 'GET_SUDOKU_ERROR';

export const CHECK_SUDOKU_STARTED_SUCCESS = 'CHECK_SUDOKU_STARTED_SUCCESS';
export const CHECK_SUDOKU_STARTED_ERROR = 'CHECK_SUDOKU_STARTED_ERROR';

export const UPDATE_HISTORY_ENTRY_SUCCESS = 'UPDATE_HISTORY_ENTRY_SUCCESS';
export const UPDATE_HISTORY_ENTRY_ERROR = 'UPDATE_HISTORY_ENTRY_ERROR';