export const API = {
  HISTORY_ENTRY_EXISTS: 'history/sudoku/',
  GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY: 'sudoku/random/difficulty/'
};

export const GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_SUCCESS = 'GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_SUCCESS';
export const GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_ERROR = 'GET_RANDOMIZED_SUDOKU_BY_DIFFICULTY_ERROR';